'use client';
import { ArrowRight, BookOpen, Boxes, FolderSearch, GitBranch } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
const scenarios = [
  { id: 'simples', label: 'Tarefa simples', role: 'Execução direta', copy: 'Uma correção textual delimitada pode ser resolvida pelo próprio agente. Não há necessidade de criar uma equipe para cada pedido.', nodes: ['Instruções do projeto', 'Correção local', 'Verificação proporcional'] },
  { id: 'especialista', label: 'Com especialista', role: 'Conhecimento específico', copy: 'Em uma alteração de interface, por exemplo, a Workflow procura orientações locais de UX, aplica a skill disponível e delega apenas se houver uma responsabilidade independente.', nodes: ['Perfil local de UX', 'Skill de design disponível', 'Consulta ou execução delimitada'] },
];
export function SpecialistDiscovery() : React.JSX.Element {
  return <section className="specialists shell"><div className="section-heading"><span className="section-number">02 / ESPECIALISTAS</span><h2>A competência certa.<br /><em>Quando ela faz diferença.</em></h2><p>O projeto orienta a descoberta. A tarefa determina quem participa.</p></div><div className="discovery-order"><div><FolderSearch /><span>01</span><strong>Contexto local</strong><p>Instruções e perfis do projeto.</p></div><ArrowRight /><div><BookOpen /><span>02</span><strong>Skills disponíveis</strong><p>Procedimentos para a tarefa.</p></div><ArrowRight /><div><Boxes /><span>03</span><strong>Capacidades reais</strong><p>Agentes e ferramentas do host.</p></div></div><Tabs defaultValue="simples"><TabsList variant="line" className="site-tabs" aria-label="Participação dos especialistas">{scenarios.map(item => <TabsTrigger key={item.id} value={item.id}>{item.label}</TabsTrigger>)}</TabsList>{scenarios.map(item => <TabsContent key={item.id} value={item.id}><div className="specialist-example"><div><span className="micro">{item.role}</span><p>{item.copy}</p></div><ol className="specialist-path">{item.nodes.map(node => <li key={node}><GitBranch size={16} /><span>{node}</span></li>)}</ol></div></TabsContent>)}</Tabs><p className="diagram-note">Um perfil Markdown orienta o trabalho. A possibilidade de executar um agente depende do host.</p></section>;
}
