import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { Header, Footer, REPOSITORY, RELEASE } from '../components/chrome';
import { CodeBlock } from '../components/examples';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ManualFaq } from './questions';
import { MobileDisclosure } from '../components/mobile-disclosure';
export const metadata: Metadata = {
  title: 'Manual técnico',
  description: 'Instalação, modos, arquitetura, especialistas, autorizações e evidências da Workflow Skill v0.1.0-alpha.1 para Codex.',
  alternates: { canonical: '/manual' },
  openGraph: { title: 'Manual técnico da Workflow Skill', description: 'Da instalação à verificação: conheça a estrutura e o uso da Workflow portátil.', url: '/manual', images: [{ url: '/og.png', width: 1731, height: 909, alt: 'Workflow — Clareza para cada etapa' }] },
  twitter: { card: 'summary_large_image', title: 'Manual técnico da Workflow Skill', description: 'Instalação, modos, estrutura e avaliação da skill para Codex.', images: ['/og.png'] },
};
const chapters = [['visao-geral','Visão geral'],['instalacao','Instalação'],['comandos','Modos e comandos'],['estrutura','Estrutura'],['especialistas','Especialistas'],['autorizacoes','Autorizações'],['continuidade','Continuidade'],['validacao','Validação'],['manutencao','Manutenção'],['duvidas','Dúvidas']];
function Chapter({ id, number, title, children }: { id: string; number: string; title: string; children: React.ReactNode }) {
  return <section className="manual-chapter" id={id}><div className="chapter-title"><span>{number}</span><h2>{title}</h2></div><div className="chapter-body">{children}</div></section>;
}
function Overview() {
  return <Chapter id="visao-geral" number="01" title="O que a Workflow faz"><p>A Workflow é um pacote de instruções que orienta como o Codex conduz uma tarefa. Ela ajuda a escolher o processo adequado, recuperar o contexto relevante, consultar especialistas disponíveis, preservar o objetivo e apresentar evidências de conclusão.</p><p>O arquivo <code>SKILL.md</code> contém o contrato principal. Referências complementares detalham contexto, especialistas e avaliação; são lidas conforme a necessidade. O pacote não oferece um runtime próprio, servidor, MCP, hooks ou permissões adicionais.</p><div className="manual-callout"><strong>Três camadas que trabalham juntas</strong><p>As instruções do usuário e do projeto definem limites. A Workflow organiza o processo. O host fornece o modelo, as ferramentas e a eventual execução de subagentes.</p></div><p>Os diagramas deste site explicam o comportamento pretendido. Eles não monitoram uma sessão real nem executam a skill no navegador. A versão documentada é a <a href={RELEASE}>v0.1.0-alpha.1</a>, experimental e distribuída sob licença MIT.</p></Chapter>;
}
const prepare = 'git clone https://github.com/edubertin/workflow-skill.git\ncd workflow-skill\ngit checkout --detach v0.1.0-alpha.1\npython -m pip install -r requirements-dev.txt\npython scripts/validate_package.py';
const install = 'python -c "from pathlib import Path; Path(\'../workflow-piloto/.agents/skills\').mkdir(parents=True, exist_ok=True)"\npython scripts/install_workflow.py --destination ../workflow-piloto/.agents/skills/workflow\npython scripts/install_workflow.py --destination ../workflow-piloto/.agents/skills/workflow --check';
function Installation() {
  return <Chapter id="instalacao" number="02" title="Instalar para avaliar"><p>As ferramentas de instalação requerem Git e Python 3.11 ou superior, com as dependências de <code>requirements-dev.txt</code>. A skill em uso contém instruções e referências; ela não precisa executar Python para orientar a conversa.</p><h3>1. Obter uma versão identificada</h3><p>Use a tag da release para manter a avaliação reproduzível. O ZIP completo da release também contém as ferramentas; o ZIP independente contém somente a pasta da skill.</p><CodeBlock label="Preparar o pacote" code={prepare} /><h3>2. Instalar em um projeto piloto</h3><p>Este exemplo cria uma pasta separada chamada <code>workflow-piloto</code>, ao lado do checkout. O destino deve ficar fora da fonte e sua pasta pai precisa existir. O instalador não sobrescreve um destino com conteúdo diferente.</p><CodeBlock label="Instalação isolada" code={install} /><h3>3. Conferir a descoberta no host</h3><p>Abra o projeto <code>workflow-piloto</code> em um novo contexto do Codex e confira se a skill foi listada. A pasta <code>.agents/skills/workflow</code> foi reconhecida pelo CLI no piloto documentado. Confirme os caminhos e as opções de descoberta do seu host na <a href="https://learn.chatgpt.com/pt-BR/docs/build-skills" target="_blank" rel="noreferrer">documentação do Codex ↗</a>.</p><p>Se já houver uma Workflow pessoal ativa, confira se o host permite desabilitá-la só para o teste ou use um ambiente de dados isolado. Não suponha que duas skills com o mesmo nome se combinam. Copiar os arquivos e passar no <code>--check</code> não demonstra que o host os carregou.</p><div className="manual-callout"><strong>Uma instalação, três verificações</strong><p>Integridade: os arquivos foram copiados corretamente. Descoberta: o host incluiu a skill no contexto. Comportamento: uma tarefa real seguiu as instruções. Verifique cada etapa separadamente.</p></div><h3>4. Fazer uma primeira consulta</h3><CodeBlock label="Primeiro pedido" code="workflow modo leitura: leia as instruções deste projeto e explique a estrutura sem alterar arquivos" /><p>O recibo <code>.workflow-install.json</code> registra versão e hashes. Quando a origem é um arquivo extraído sem Git, o recibo não atribui um commit a essa cópia. A rastreabilidade da release pode ser conferida pelos hashes publicados em <code>SHA256SUMS.txt</code>.</p></Chapter>;
}
const modes = [
 ['Contexto de projeto','workflow retome o contexto deste projeto','Estado atual, fontes e pendências, em leitura.'],
 ['Novo projeto','workflow novo projeto: organize a estrutura inicial','Estrutura proporcional ao projeto solicitado.'],
 ['Leitura','workflow modo leitura: analise este módulo','Análise sem edição de arquivos ou escrita externa.'],
 ['Investigação / spike','workflow investigue as opções antes de implementar','Achados, alternativas e incertezas restantes.'],
 ['Especificação','workflow escreva uma spec para esta funcionalidade','Objetivo, regras, escopo e critérios de aceite.'],
 ['Implementação','workflow implemente a correção deste issue','Mudança delimitada e verificação.'],
 ['Refatoração','workflow refatore preservando o comportamento','Melhoria estrutural e checks relevantes.'],
 ['QA / revisão','workflow revise esta alteração e execute os checks','Evidências, falhas e limitações.'],
 ['Publicação / release','workflow prepara no GitHub','Fluxo autorizado pelas regras do usuário e do projeto.'],
 ['Estrutura de repositório','workflow avalie a organização deste repositório','Inventário em leitura e recomendação por etapas.'],
];
function MobileModes(): React.JSX.Element {
  return <div className="manual-mode-list">{modes.map(([mode, command, outcome]) => <article className="manual-mode" key={mode}><h3>{mode}</h3><dl><dt>Pedido de exemplo</dt><dd><code>{command}</code></dd><dt>Resultado esperado</dt><dd>{outcome}</dd></dl></article>)}</div>;
}
function Commands() {
  return <Chapter id="comandos" number="03" title="Modos e comandos"><p>Workflow interpreta linguagem natural. Os exemplos em português não constituem uma sintaxe obrigatória. Para uma tarefa concreta, ela seleciona o processo diretamente, sem abrir um menu a cada pedido.</p><div className="manual-table"><Table><TableHeader><TableRow><TableHead>Modo</TableHead><TableHead>Pedido de exemplo</TableHead><TableHead>Resultado esperado</TableHead></TableRow></TableHeader><TableBody>{modes.map(([mode, command, outcome]) => <TableRow key={mode}><TableCell>{mode}</TableCell><TableCell><code>{command}</code></TableCell><TableCell>{outcome}</TableCell></TableRow>)}</TableBody></Table></div><MobileModes /><h3>Quando você só quer ver as opções</h3><CodeBlock label="Abrir o menu" code="workflow" /><p>Sem uma tarefa concreta, esse pedido mostra dez opções, incluindo avaliação de agentes e skills. Mostrar o menu não requer inspecionar o projeto. Uma seleção escolhe o processo e mantém os limites de autorização aplicáveis.</p><h3>Risco e tamanho do processo</h3><p>Uma pequena alteração local costuma pedir verificação simples. Componentes e mudanças de comportamento pedem um plano curto. Auth, pagamentos, acesso a dados, produção e operações destrutivas exigem as regras, evidências e aprovações próprias do contexto. Classificar risco não concede permissão.</p></Chapter>;
}
const tree = 'workflow-skill/\n├── skills/workflow/\n│   ├── SKILL.md\n│   ├── LICENSE\n│   ├── agents/openai.yaml\n│   └── references/\n│       ├── project-context-and-structure.md\n│       ├── specialist-discovery.md\n│       ├── model-evaluation-protocol.md\n│       ├── workflow-regression-suite.md\n│       └── gpt-5p6-evaluation-profile.md\n├── .codex-plugin/plugin.json\n├── scripts/\n│   ├── install_workflow.py\n│   ├── validate_package.py\n│   └── package_support.py\n├── tests/test_package.py\n├── docs/agents/\n└── .github/workflows/ci.yml';
const fileRoles = [['SKILL.md','Contrato operacional, modos, contexto, descoberta, verificação e autoridade.'],['agents/openai.yaml','Metadados de apresentação da skill para o host.'],['project-context-and-structure.md','Retomada de contexto, criação de projetos e auditoria de estrutura.'],['specialist-discovery.md','Ordem de descoberta e responsabilidades por especialidade.'],['model-evaluation-protocol.md','Protocolo para comparações controladas e evidência observável.'],['workflow-regression-suite.md','37 cenários documentados de regressão.'],['gpt-5p6-evaluation-profile.md','Referência histórica condicional para avaliações explícitas de GPT-5.6. Não define um modelo padrão.'],['.codex-plugin/plugin.json','Empacotamento da mesma skill como plugin; validar o manifesto não equivale a instalar no diretório de plugins.']];
function Structure() {
  return <Chapter id="estrutura" number="04" title="Estrutura do pacote"><p>O repositório reúne a skill distribuível e as ferramentas de manutenção. A instalação independente tem oito arquivos: o contrato, a licença, o YAML e cinco referências.</p><CodeBlock label="Mapa do repositório" code={tree} format="tree" /><dl className="file-roles">{fileRoles.map(([name, description]) => <div key={name}><dt><code>{name}</code></dt><dd>{description}</dd></div>)}</dl><p>Os dois perfis em <code>docs/agents/</code> orientam manutenção e revisão da avaliação deste repositório. Eles não são agentes automaticamente registrados no host e não copiam o conjunto pessoal de especialistas do autor.</p><a className="text-link" href={REPOSITORY + '/tree/main/skills/workflow'} target="_blank" rel="noreferrer">Explorar os arquivos no GitHub <ArrowUpRight size={15} /></a></Chapter>;
}
function Specialists() {
  return <Chapter id="especialistas" number="05" title="Contexto e especialistas"><p>A leitura começa pelas instruções aplicáveis do projeto. Em seguida, a Workflow busca trechos relevantes de PROJECT.md, README, specs, ADRs e documentação. Esse uso direcionado de arquivos locais é chamado de RAG-Lite; não requer um serviço de embeddings ou um banco vetorial.</p><p>Quando a tarefa exige uma especialidade, a descoberta respeita esta ordem: orientações e perfis locais; uma skill disponível para o procedimento; capacidades reais de ferramentas e agentes do host. Um especialista adicional precisa trazer julgamento distinto ou assumir uma parte independente.</p><CodeBlock label="Exemplo de orientação em AGENTS.md" code={'Antes de alterar cálculos, leia docs/agents/calculation.md.\nAntes de revisar o cadastro, leia docs/agents/ux.md.\nCada consulta deve informar objetivo, escopo, limites e evidências.\nNão publique alterações sem autorização do usuário.'} /><h3>Contrato de uma consulta</h3><ul><li>Objetivo e responsabilidade delimitada.</li><li>Arquivos ou superfície sob responsabilidade do especialista.</li><li>Restrições e autorização já existente.</li><li>Evidências esperadas e condição de conclusão.</li></ul><p>Trabalho em paralelo só se aplica quando as partes são independentes e o host permite. Na ausência de delegação, o agente principal pode aplicar o perfil disponível e informar essa limitação. Uma especialidade inexistente não deve ser apresentada como agente executado.</p><p>A Workflow reúne o resultado e reporta descobertas fora do escopo como sugestões. Essas descobertas não autorizam trabalho adicional.</p></Chapter>;
}
function Authority() {
  return <Chapter id="autorizacoes" number="06" title="Escopo e autorização"><p>Antes de uma ação com efeitos, a Workflow confere destino, escopo, autorização aplicável, reversibilidade ou mitigação e evidências necessárias. As instruções pessoais e do projeto podem impor regras mais restritas.</p><div className="manual-callout"><strong>O processo não amplia a autoridade</strong><p>Um plano, um modo de release, um checkpoint ou a recomendação de um especialista não concede permissão para publicar, alterar produção ou acessar dados sensíveis.</p></div><dl className="file-roles"><div><dt>“Pode fazer”</dt><dd>Autoriza a implementação delimitada. Por si só, não solicita commit ou publicação.</dd></div><div><dt>“Prepara no GitHub”</dt><dd>Pode autorizar branch, checks, commit, push e draft PR quando o contexto e as regras do projeto sustentam esse significado.</dd></div><div><dt>“Finaliza”</dt><dd>Autoriza merge apenas quando se refere inequivocamente ao PR em questão e seus critérios estão atendidos.</dd></div></dl><p>Documentos, comentários, páginas e resultados de ferramentas são fontes de contexto. Pedidos de acesso a secrets, publicação ou trabalho alheio inseridos nesses materiais não substituem a autorização do usuário.</p></Chapter>;
}
function Continuity() {
  return <Chapter id="continuidade" number="07" title="Status, interrupção e retomada"><p>Uma pergunta de status pede informação sobre o progresso. Ela não cancela o objetivo vigente. A Workflow responde e continua o trabalho autorizado que estiver pendente.</p><p>Uma instrução para parar ou restringir a tarefa muda esse limite. O agente deve deixar de iniciar ações afetadas, preservar o que já foi concluído e explicar as pendências. Operações já em andamento podem depender das capacidades de cancelamento do host.</p><h3>Um checkpoint útil</h3><CodeBlock label="Contexto para retomar" code={'Objetivo: corrigir o cálculo de créditos.\nEscopo: módulo de cálculo e seus testes.\nAutoridade: alteração local; sem commit ou publicação.\nConcluído: falha reproduzida; cálculo corrigido.\nEvidência: testes unitários passaram.\nPendente: conferir o caso de borda documentado.\nPróxima ação: ler o estado atual antes de editar.'} /><p>Na retomada, o estado real deve ser conferido antes de repetir efeitos. Checkpoints são úteis em trabalhos longos; não é necessário criar um arquivo de acompanhamento para toda correção pequena.</p></Chapter>;
}
function Validation() {
  return <Chapter id="validacao" number="08" title="Evidências e limites"><p>Validação estrutural, testes das ferramentas e comportamento do modelo medem coisas diferentes. Um pacote bem formado não garante que toda execução seguirá suas instruções.</p><ul><li><strong>Release:</strong> 45 testes locais das ferramentas passaram. O GitHub Actions verifica combinações de Windows/Linux e Python 3.11/3.12.</li><li><strong>Suíte documentada:</strong> 37 cenários. A revisão estática registrou 35 compatíveis e 2 inconclusivos; isso não representa 37 execuções completas.</li><li><strong>Piloto de 05/09/2026:</strong> oito arquivos íntegros, recibo conferido e uma única Workflow portátil reconhecida automaticamente pelo Codex CLI 0.130.0-alpha.5 em contexto isolado.</li><li><strong>Casos locais do piloto:</strong> correção de cálculo com reprodução da falha, revisão em leitura com perfil de UX e respeito a regras restritivas de publicação. Somente dois arquivos autorizados mudaram.</li></ul><div className="manual-callout"><strong>Descoberta e execução foram verificadas em ambientes distintos</strong><p>O CLI isolado não estava autenticado. Os três casos comportamentais usaram um subagente de contexto novo com a candidata indicada por caminho. Eles não demonstram execução autenticada no mesmo CLI que descobriu a skill.</p></div><p>Continuam pendentes a ativação equivalente no desktop e pelo diretório de plugins, a execução completa da suíte, repetições independentes dos casos sensíveis e a qualificação estável. A instalação pessoal do piloto permaneceu intacta.</p><p>Modelo, esforço, tokens, custo e latência não foram verificados nesse conjunto de casos. Não há alegação de superioridade de modelo, compatibilidade universal ou confiabilidade estatística.</p><div className="doc-links"><a href={REPOSITORY + '/blob/main/docs/evaluation.md'} target="_blank" rel="noreferrer">Evidências da release ↗</a><Link href="/docs/piloto-portatil.md">Relatório do piloto ↓</Link></div></Chapter>;
}
function Maintenance() {
  return <Chapter id="manutencao" number="09" title="Atualizar e contribuir"><p>Antes de atualizar uma instalação, escolha a versão, compare as mudanças e guarde os arquivos atuais. Instale a candidata em outro destino explícito, confira a integridade e valide tarefas representativas em um contexto novo.</p><p>Preferências pessoais — idioma, regras de commit e push, padrões de projeto e direção visual — devem permanecer nas instruções do usuário ou do projeto. A atualização da skill não deve reescrevê-las.</p><CodeBlock label="Checks do repositório da skill" code={'python scripts/validate_package.py\npython -m unittest discover -s tests -v'} /><p>Para alterações relevantes de comportamento, leia o protocolo de avaliação, fixe os critérios e preserve falhas e retestes. Uma alteração estreita pede o subconjunto pertinente; mudanças amplas exigem cobertura maior. Diferencie resultado observado, simulação e casos inconclusivos.</p><p>A MIT permite uso, modificação e distribuição, inclusive comercial, mantendo o aviso de copyright e o texto da licença. Materiais externos continuam sujeitos às respectivas licenças. Consulte o <a href={REPOSITORY + '/blob/main/LICENSE'} target="_blank" rel="noreferrer">texto integral ↗</a>.</p><div className="doc-links"><a href={REPOSITORY + '/issues'} target="_blank" rel="noreferrer">Relatar uma questão ↗</a><a href={REPOSITORY + '/blob/main/docs/releasing.md'} target="_blank" rel="noreferrer">Processo de release ↗</a><a href={REPOSITORY + '/blob/main/PROVENANCE.md'} target="_blank" rel="noreferrer">Origem do pacote ↗</a></div></Chapter>;
}
export default function ManualPage() : React.JSX.Element {
  return <><Header /><main className="manual shell" id="conteudo"><div className="manual-heading"><Link className="text-link" href="/"><ArrowLeft size={16} /> Voltar à apresentação</Link><span className="eyebrow">DOCUMENTAÇÃO / v0.1.0-alpha.1</span><h1>Por dentro da<br /><em>Workflow.</em></h1><p>Da instalação ao uso. Um guia para entender o processo, explorar a estrutura e avaliar a skill no seu contexto.</p></div><nav className="manual-index" aria-label="Índice do manual"><span className="micro">NESTE MANUAL</span><ol>{chapters.map(([id, title], index) => <li key={id}><a href={'#' + id}><span>{String(index + 1).padStart(2,'0')}</span>{title}</a></li>)}</ol></nav><MobileDisclosure label="Neste manual" className="manual-mobile-index"><nav aria-label="Índice do manual"><ol>{chapters.map(([id, title], index) => <li key={id}><a href={'#' + id}><span>{String(index + 1).padStart(2,'0')}</span>{title}</a></li>)}</ol></nav></MobileDisclosure><Overview /><Installation /><Commands /><Structure /><Specialists /><Authority /><Continuity /><Validation /><Maintenance /><Chapter id="duvidas" number="10" title="Dúvidas frequentes"><ManualFaq /></Chapter><div className="manual-bottom"><a className="text-link" href="#conteudo">Voltar ao início ↑</a><span>Referência: v0.1.0-alpha.1 · Atualizado em 05/09/2026</span></div></main><Footer /></>;
}
